sudo: required
dist: trusty
language: python

cache:
    apt
    pip

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - sudo apt-get update
  - sudo apt-get install uuid-dev libuuid1
  - pip install wheel cython

install:
  - python setup.py build_ext bdist_wheel
  - pip install dist/*.whl

script:
  - python -c "import pyzyre; print(pyzyre.__version__)"
  - python -c "import zyre; print(zyre.Zyre)"
  - python -c "import czmq; print(czmq.Zactor)"

notifications:
    email:
        on_success: never
